### ISSUE TITLE
(Probably)basic configuration problem

### ISSUE THREAD

**Issue by Lupi00** [danielolsson100/ha-nibedvc10#2]
A total beginner who is stuck. The solution is probably easy but I cant seem to get it to work. 
I am using a raspberry pi 4. 

This is added to the configuration.yaml as I understand it. 

```
# Loads default set of integrations. Do not remove.
default_config:
python_script:
  
  - platform: command_line
    switches:
      nibe_dvc10_office:
        friendly_name: NIBE DVC 10 - Office
        command_on: "python3 /config/python_scripts/nibe_dvc10.py 192.168.1.20 start"
        command_off: "python3 /config/python_scripts/nibe_dvc10.py 192.168.1.20 stop"
```

The script is nibe_dvc10.py in the folder python_scripts

And I get this when I try to validate the configuration.yaml before I restart the home assistant. 

`Invalid config for [python_script]: expected dict for dictionary value @ data['python_script']. Got [{'platform': 'command_line', 'switches': {'nibe_dvc10_office': {'friendly_name': 'NIBE DVC 10 - Office', 'command_on': 'python3 /config/python_scripts/nibe_dvc10.py 192.168.1.20 start', 'command_off': 'python3 /config/python_scripts/nibe_dvc10.py 192.168.1.20 stop'}}}]. (See /config/configuration.yaml, line 3).`

Anyone who can guide me to get this to work? 

thank you
